-- Create the OEE records table
create table public.registros_oee (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Inputs (from Orange cells)
    fecha date not null,
    linea text not null,
    turno text not null,
    modelo text,
    tiempo_programado_min integer default 0,
    rate_teorico float default 0,
    producido integer default 0,
    rechazos_fugas integer default 0,
    
    -- Failure Modes (Orange cells)
    setup_excesivo integer default 0,
    falla_mecanica integer default 0,
    falla_electrica integer default 0,
    falla_chamber integer default 0,
    ajuste_no_programado integer default 0,
    falta_material integer default 0,

    -- Calculated Fields (Backend Logic)
    tiempo_muerto integer default 0,
    tiempo_funcionamiento integer default 0,
    disponibilidad float default 0,
    rendimiento float default 0,
    calidad float default 0,
    oee float default 0
);
